[package]
name = "microbin"
version = "1.2.0"
edition = "2021"
authors = ["Daniel Szabo <daniel.szabo99@outlook.com>"]
license = "BSD-3-Clause"
description = "Simple, performant, configurable, entirely self-contained Pastebin and URL shortener."
readme = "README.md"
homepage = "https://github.com/szabodanika/microbin"
repository = "https://github.com/szabodanika/microbin"
keywords = ["pastebin", "pastabin", "microbin", "actix", "selfhosted"]
categories = ["pastebins"]

[dependencies]
actix-web = "4"
actix-files = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.95"
bytesize = { version = "1.1", features = ["serde"] }
askama = "0.12"
askama-filters = { version = "0.1.3", features = ["chrono"] }
chrono = "0.4.24"
rand = "0.8.5"
linkify = "0.9.0"
clap = { version = "3.1.12", features = ["derive", "env"] }
actix-multipart = "0.4.0"
futures = "0.3"
sanitize-filename = "0.4.0"
log = "0.4"
env_logger = "0.10.0"
actix-web-httpauth = "0.6.0"
lazy_static = "1.4.0"
syntect = "5.0"
qrcode-generator = "4.1.6"
rust-embed = "6.6.0"
mime_guess = "2.0.4"
harsh = "0.2"

[profile.release]
lto = true
strip = true
